# Generated by Django 5.1.7 on 2025-03-31 06:00

from django.db import migrations
from ..models import UserType

def add_user_types(apps, schema_editor):
    UserType(id=1, name="Admin").save()
    UserType(id=2, name="Driver").save()

class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(add_user_types)
    ]
