# Generated by Django 5.1.7 on 2025-04-04 12:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0002_auto_20250331_0600'),
    ]

    operations = [
        migrations.CreateModel(
            name='DutyType',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='DriverLog',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField()),
                ('total_miles', models.IntegerField()),
                ('carrier', models.CharField(max_length=100)),
                ('main_office_address', models.CharField(max_length=200)),
                ('signature', models.TextField()),
                ('co_driver', models.CharField(max_length=100)),
                ('time_zone', models.PositiveSmallIntegerField()),
                ('document_number', models.CharField(max_length=100)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='users.user')),
            ],
        ),
        migrations.CreateModel(
            name='GraphGrid',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('time', models.TimeField()),
                ('remark', models.CharField(max_length=200)),
                ('duty_type_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='driver_logs.dutytype')),
                ('log_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='driver_logs.driverlog')),
            ],
        ),
        migrations.CreateModel(
            name='Truck',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('truck_number', models.CharField(max_length=100)),
                ('trailer_number', models.CharField(max_length=100)),
                ('log_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='driver_logs.driverlog')),
            ],
        ),
    ]
