# Generated by Django 5.1.7 on 2025-04-04 12:53

from django.db import migrations
from ..models import DutyType

def add_duty_types(apps, schema_editor):
    DutyType(id = 1, name = 'Off_Duty').save()
    DutyType(id = 2, name = 'Sleeper_Berth').save()
    DutyType(id = 3, name = 'Driving').save()
    DutyType(id = 4, name = 'On_Duty').save()


class Migration(migrations.Migration):

    dependencies = [
        ('driver_logs', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(add_duty_types)
    ]
