# Generated by Django 5.1.7 on 2025-04-04 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver_logs', '0002_auto_20250404_1253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driverlog',
            name='time_zone',
            field=models.CharField(max_length=7),
        ),
    ]
