# Generated by Django 5.1.7 on 2025-04-11 08:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver_logs', '0004_alter_driverlog_id_alter_graphgrid_id_alter_truck_id'),
        ('users', '0005_user_is_active_alter_user_user_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driverlog',
            name='user_id',
        ),
        migrations.AddField(
            model_name='driverlog',
            name='driver',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.RESTRICT, related_name='driver', to='users.user'),
        ),
        migrations.AlterField(
            model_name='driverlog',
            name='co_driver',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='co_driver', to='users.user'),
        ),
    ]
