# Generated by Django 5.1.7 on 2025-04-11 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver_logs', '0005_remove_driverlog_user_id_driverlog_driver_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driverlog',
            name='date',
            field=models.DateField(),
        ),
    ]
