# Generated by Django 5.1.7 on 2025-04-11 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver_logs', '0006_alter_driverlog_date'),
        ('users', '0005_user_is_active_alter_user_user_name'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='driverlog',
            constraint=models.UniqueConstraint(models.F('date'), models.F('driver'), name='date_driver_unique_constraint'),
        ),
    ]
