# Generated by Django 5.1.7 on 2025-04-11 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver_logs', '0007_driverlog_date_driver_unique_constraint'),
        ('users', '0005_user_is_active_alter_user_user_name'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='driverlog',
            name='date_driver_unique_constraint',
        ),
        migrations.RenameField(
            model_name='truck',
            old_name='log_id',
            new_name='driver_log',
        ),
        migrations.AddConstraint(
            model_name='driverlog',
            constraint=models.UniqueConstraint(models.F('driver'), models.F('date'), name='driver_date_unique_constraint'),
        ),
        migrations.AddConstraint(
            model_name='truck',
            constraint=models.UniqueConstraint(models.F('driver_log'), models.F('truck_number'), name='driver_log-truck_number-unique_constraint'),
        ),
    ]
