# Generated by Django 5.1.7 on 2025-04-12 07:50

import driver_logs.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver_logs', '0008_remove_driverlog_date_driver_unique_constraint_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='driverlog',
            name='truck_info',
            field=models.JSONField(default=driver_logs.models.DriverLog.truck_info_default),
        ),
        migrations.DeleteModel(
            name='Truck',
        ),
    ]
