# Generated by Django 5.1.7 on 2025-04-12 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver_logs', '0010_alter_driverlog_truck_info'),
    ]

    operations = [
        migrations.RenameField(
            model_name='graphgrid',
            old_name='log_id',
            new_name='driver_log',
        ),
        migrations.RenameField(
            model_name='graphgrid',
            old_name='duty_type_id',
            new_name='duty_type',
        ),
        migrations.AddField(
            model_name='graphgrid',
            name='sequence',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
