# Generated by Django 5.1.7 on 2025-04-12 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver_logs', '0011_rename_log_id_graphgrid_driver_log_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='graphgrid',
            constraint=models.UniqueConstraint(models.F('sequence'), models.F('driver_log'), name='sequence-driver_log-unique_constraint'),
        ),
    ]
