# Generated by Django 5.1.7 on 2025-04-14 10:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver_logs', '0012_graphgrid_sequence_driver_log_unique_constraint'),
    ]

    operations = [
        migrations.AddField(
            model_name='driverlog',
            name='prev_driver_log',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='previous_driver_log', to='driver_logs.driverlog'),
        ),
        migrations.AlterField(
            model_name='graphgrid',
            name='remark',
            field=models.JSONField(null=True, verbose_name='Remark'),
        ),
    ]
